### ISSUE TITLE
Menüberschriften eingerückt?

### ISSUE THREAD

**Issue by BITS-Editor** [BITS-Training/BITS-hugo#21]
Im Menü sind die zweiten Zeilen der Unterpunkte der Lektion "E-Mail"
Übermittlung von E-Mails im Internet
und
Erste Hilfe bei fehlgeleiteten Informationen
NICHT eingerückt. Kann man das fixen?

**Comment by andi-blafasl** [comment]
Das liegt an zu langem Text. Wenn die Zeile umgebrochen wird, dann greift bei der zweiten Zeile das "text-indent" nicht.

```css
#sidebar ul li li {
    padding-left: 1rem;
    text-indent: 0.2rem;
}
```

Nimmt man des "text-indent" raus, dann sieht es normal aus. Was das für weitere Auswirkungen hat muss ich noch anschauen.
